rancher/gke-operator

controller/gke-cluster-config-handler.go
internal/gke/update.go

It is valid to create a GKE cluster with the kubernetes version, node
pool version, or node pool image type set to "". GKE will set defaults
on the backend. However, it causes problems during the update cycle. The
validateAndUpdate function on the controller cannot check whether "" is
semver compliant, and the Update* functions cannot set "" as a desired
value to update to. This change adds allowances for certain string
parameters to be empty. Also restructures the
UpdateMasterKubernetesVersion to be more Go-idiomatic by returning early
if possible.
https://github.com/rancher/rancher/issues/31704

Fix controller sync for empty version/image string

---

.drone.yml
Dockerfile.dapper
charts/gke-operator-crd/Chart.yaml
charts/gke-operator-crd/templates/crds.yaml
charts/gke-operator/Chart.yaml
charts/gke-operator/templates/NOTES.txt
charts/gke-operator/templates/_helpers.tpl
charts/gke-operator/templates/clusterrole.yaml
charts/gke-operator/templates/clusterrolebinding.yaml
charts/gke-operator/templates/deployment.yaml
charts/gke-operator/templates/serviceaccount.yaml
charts/gke-operator/values.yaml
pkg/codegen/main.go
scripts/package
scripts/package-helm
scripts/version

These changes are the first step in moving gke-operator to
rancher/charts. The chart is not included here and is built as a
part of the CI process.

Create chart and include in CI

---

controller/gke-cluster-config-handler.go

Previously, if a user tried to create two nodepools with the same name,
an update loop would commence where gke-operator would continually try
to upgrade a nodepool in GKE that had two configs in Rancher.
After this change, the collision will be detected and no update will
happen until the collision is fixed.
Issue:
https://github.com/rancher/rancher/issues/32493

Error on nodepool name collisions

---

pkg/apis/gke.cattle.io/v1/types.go

Temporarily revert a85378a8 in order to make a release for 522d7c84
without bringing in the more complex type changes.

Revert "Set norman type to 'nullablestring' for *strings"

---

charts/gke-operator-crd/Chart.yaml
charts/gke-operator/Chart.yaml
charts/gke-operator/templates/_helpers.tpl
charts/gke-operator/templates/deployment.yaml
charts/gke-operator/values.yaml

This adds new annotations for app and marketplace UI changes. It also adding the correct tolerations and selectors for running in a mixed workload cluster.
* https://github.com/rancher/rancher/issues/36401
* https://github.com/rancher/dashboard/issues/5137
Verified that it will deploy in a mixed workload cluster successfully after the changes.

Changes required to support mixed workload clusters.

---

charts/gke-operator/templates/deployment.yaml

Current nodeSelectors and tolerations are broken if you try supplying anything except default.
Larger PR: https://github.com/rancher/charts/pull/1813

Fix nodeSelectors and tolerations

---

go.mod
go.sum

Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

Update `golang.org/x/text` dependency

---

Dockerfile.dapper
package/Dockerfile

- Align to standardized BCI
- Bump to 15.4 as 15.3 is EOL

Change to BCI and bump

---

Dockerfile.dapper
package/Dockerfile

Backport of https://github.com/rancher/gke-operator/pull/81

[release/v1.1] Change to BCI and bump

---

.gitignore
controller/gke-cluster-config-handler.go
pkg/gke/update.go

Issue: https://github.com/rancher/gke-operator/issues/85

Adding support for updating labels in node pools

---

.github/workflows/scan.yaml

Adds image scanning with Trivy.

feat: add image scanning workflow

---

Makefile
controller/gke-cluster-config-handler.go
go.mod
pkg/gke/client.go
pkg/gke/create.go
pkg/gke/create_test.go
pkg/gke/delete.go
pkg/gke/delete_test.go
pkg/gke/services/gke.go
pkg/gke/services/mock_services/gke_mock.go
pkg/gke/suite_test.go
pkg/gke/update.go
pkg/gke/update_test.go

Issue: https://github.com/rancher/gke-operator/issues/158

Adding unit test for gke-operator

---

controller/gke-cluster-config-handler.go
pkg/apis/gke.cattle.io/v1/types.go

Issue: https://github.com/rancher/gke-operator/issues/146

Add kubebuilder validation markers to the GKEClusterConfig type

---

pkg/gke/create.go
pkg/gke/create_test.go

Issue: https://github.com/rancher/gke-operator/issues/122
cc: @rancher/highlander 
(cherry picked from commit 1a6e7d353bd44d737cdeabc0f1b7c09fc4a84aec)

[2.8] Check for duplicate names for NodePools

---

.github/workflows/build.yaml
.github/workflows/lint.yaml
.github/workflows/scan.yaml
.github/workflows/unit.yaml
.github/workflows/update-rancher-charts.yaml
.github/workflows/update-rancher-dep.yaml

We want to run unit tests.
Issue #https://github.com/rancher/gke-operator/issues/93
**Checklist**:

Add unit test workflow for CI

---

test/e2e/templates/basic-cluster.yaml

Issue #https://github.com/rancher/gke-operator/issues/98
**Checklist**:

Fixing e2e tests for GKE main branch

---

test/e2e/basic_cluster_test.go
test/e2e/templates/basic-cluster.yaml

Issue: https://github.com/rancher/gke-operator/issues/97
Issue #
**Checklist**:

Add more e2e tests scenarios

---

.github/workflows/apidiff.yaml
.github/workflows/build.yaml
.github/workflows/lint.yaml
.github/workflows/unit.yaml
.github/workflows/verify.yaml
Dockerfile.dapper
go.mod

(cherry picked from commit 22d447265a86e5706bf3ce4b4654c420f5ccbe18)
Issue #
**Checklist**:

[v2.9] Bump go version to 1.21

---

.github/workflows/apidiff.yaml
.github/workflows/build.yaml
.github/workflows/lint.yaml
.github/workflows/unit.yaml
Dockerfile.dapper
go.mod
go.sum

(cherry picked from commit 22d447265a86e5706bf3ce4b4654c420f5ccbe18)
Issue #
**Checklist**:

[v2.8] Bump go version to 1.21

---

.github/dependabot.yaml

Ignore github.com/rancher/rancher/pkg/apis by dependabot

---

go.mod
go.sum

[v2.8] Revert go version v1.20 for v2.8

---

Makefile
go.mod
go.sum
test/e2e/config/config.yaml
test/e2e/suite_test.go

Fixes for e2e tests

---

.github/workflows/e2e.yaml
Makefile

Fixes for e2e workflow

---

Makefile
controller/external.go
controller/gke-cluster-config-handler.go
controller/gke-cluster-config-handler_test.go
controller/suite_test.go
go.mod
go.sum
pkg/gke/create.go
pkg/gke/create_test.go
pkg/gke/delete_test.go
pkg/test/cleanup.go
pkg/test/envtest.go

Issue #https://github.com/rancher/gke-operator/issues/92
This PR will break Rancher integration this is why we have also get merge PR for Rancher https://github.com/rancher/rancher/pull/44253
**Checklist**:

Add cluster config handler unit tests

---

.github/dependabot.yaml

This will reduce number of dependabot PRs required to review for the operators.
Issue #
**Checklist**:

Group dependabot updates for all branches

---

.github/workflows/release.yaml

Read Docker credentials in secure way

---

.github/workflows/lint.yaml
.github/workflows/scan.yaml
.github/workflows/unit.yaml
.github/workflows/verify.yaml

Issue https://github.com/rancher/gke-operator/issues/373
**Checklist**:

Run CI jobs on release branches

---

.github/workflows/release.yaml

Update release.yaml with new step

---

.github/workflows/release.yaml

Push only when push tags

---

.github/workflows/release.yaml

Checkout correct tag version before release

---

.github/workflows/release.yaml
Makefile

Update secret names

---

Dockerfile.dapper

(cherry picked from commit 697e939cbbcf2a41f9257237ae9a512fe1ecac2e)
Issue #
**Checklist**:

[v2.9] Bump go version to v1.21.10

---

charts/gke-operator/templates/deployment.yaml

Issue: https://github.com/rancher/aks-operator/issues/482
Issue #
**Checklist**:

Update systemDefaultRegistry in helm chart

---

charts/gke-operator/templates/deployment.yaml

Issue: https://github.com/rancher/aks-operator/issues/482 (cherry picked from commit 7134cbcdb99f5cf6aa8fc0c0bbf5d66f8c815949)
Issue #
**Checklist**:

[v2.9] Update systemDefaultRegistry in helm chart

---

charts/gke-operator/templates/deployment.yaml

Issue: https://github.com/rancher/aks-operator/issues/482 (cherry picked from commit 7134cbcdb99f5cf6aa8fc0c0bbf5d66f8c815949)
Issue #
**Checklist**:

[v2.8] Update systemDefaultRegistry in helm chart

---

go.mod
go.sum

Downgrade controller-runtime dependency to v1.15.3

---

go.mod
go.sum

(cherry picked from commit fdc1e5d1b2a7291be831581a494f8c99ea4a78c4)
Issue #
**Checklist**:

[v2.9] Downgrade controller-runtime dependency to v1.15.3

---

go.mod

[v2.9] Remove toolchain from go.mod

---

Dockerfile.dapper

Bumped Go version to fix CVE-2024-24790.
**Checklist**:

fix: Bump Go version to fix CVE-2024-24790

---

.github/workflows/update-rancher-charts.yaml

The workflow currently fails to create a branch because it lacks GitHub credentials for the bot.
Issue #96 
**Checklist**:

fix: Use bot token to create a branch

---

.github/workflows/update-rancher-charts.yaml

Specify repo for target PR
Issue #96 
**Checklist**:

ci: Specify repo for target PR

---

.github/workflows/update-rancher-charts.yaml
.github/workflows/update-rancher-dep.yaml

Add CI workflow used to update `rancher/rancher` with a new operator version.
Issue #96 
**Checklist**:

ci: Add workflow used to update `rancher/rancher` with a new operator version

---

charts/gke-operator/templates/deployment.yaml

1. Restrict container from acquiring additional privileges (`securityContext.allowPrivilegeEscalation`)
2. Mount container's root filesystem as read only (`securityContext.readOnlyRootFilesystem`)
3. Ensure that container won't be started as privileged container (`securityContext.privileged`)
Issue: https://github.com/rancher/aks-operator/issues/591
Issue #
**Checklist**:

Improve securityContext for operator Deployment

---

charts/gke-operator/templates/deployment.yaml

1. Restrict container from acquiring additional privileges (`securityContext.allowPrivilegeEscalation`)
2. Mount container's root filesystem as read only (`securityContext.readOnlyRootFilesystem`)
3. Ensure that container won't be started as privileged container (`securityContext.privileged`)
Issue: https://github.com/rancher/aks-operator/issues/591 (cherry picked from commit 05135ed725fb8f0b70cd74b71066953330615603)
Issue #
**Checklist**:

[v2.9] Improve securityContext for operator Deployment

---

.github/workflows/release.yaml
go.mod
package/Dockerfile
test/e2e/Dockerfile.e2e

(cherry picked from commit 2dea3652fa341065d4ddf47c34158beba07654cf)
Issue #
**Checklist**:

[v2.8] Enforce latest go version and bump to bci image to 15.6

---

controller/gke-cluster-config-handler.go
controller/gke-cluster-config-handler_test.go
pkg/gke/create.go
pkg/gke/update.go

kind/enhancement
1. Enhance the log to better understand updates happening in the cluster.
2. Use both clusterName and clusterID in the logs.
Issue https://github.com/rancher/gke-operator/issues/493
Issue https://github.com/rancher/gke-operator/issues/494
**Checklist**:

Enhance the logs

---

go.mod

Bump Kubernetes to v1.29.7

---

.github/dependabot.yaml

Drop v2.7 branch for dependabot

---

go.mod

(cherry picked from commit ab570a94c7a53a5a5d9da20686051cb5a1cabec1)
Issue #
**Checklist**:

[v2.9] Bump Kubernetes to v1.29.7

---

controller/gke-cluster-config-handler.go

When the status gets updated, if a conflict error happens, it will retry the operation again.
Issue #
**Checklist**:

fix: Retry operation on conflict

---

controller/gke-cluster-config-handler.go

(cherry picked from commit abaa9dc0d39b9974f0aa7b97fba5afc3a23fe851)
When the status gets updated, if a conflict error happens, it will retry the operation again.
Issue #
**Checklist**:

[v2.9] fix: Retry operation on conflict

---

controller/gke-cluster-config-handler.go

Reverts rancher/gke-operator#666

Revert "[v2.9] fix: Retry operation on conflict"

---

.github/dependabot.yaml

Ignore Google API version for Rancher v2.9

---

controller/gke-cluster-config-handler.go

(cherry picked from commit https://github.com/rancher/gke-operator/pull/679/commits/b4346aec928fddfb7a5eed1f8c804016b60b0bf0)
Reverts https://github.com/rancher/gke-operator/pull/665

Revert "[main] fix: Retry operation on conflict"

---

.github/workflows/nightly-publish.yaml

Removed an obsolete parameter from referenced workflow.
**Checklist**:

ci: Remove obsolete parameter

---

.github/dependabot.yaml
.github/workflows/e2e-workflow.yaml

Updated CI workflows for 2.10.
**Checklist**:

ci: Update workflows for 2.10

---

go.mod
go.sum

Revert bump of github.com/Masterminds/semver/v3

---

go.mod
go.sum

[v2.10] Revert bump of github.com/Masterminds/semver/v3

---

go.mod
go.sum

Bump golang.org/x/crypto to v0.31.0

---

go.mod
go.sum

[v2.9] Bump golang.org/x/crypto to v0.31.0

---

go.mod
go.sum

[v2.8] Bump golang.org/x/crypto to v0.31.0

---

go.mod
go.sum

[v2.10] Bump golang.org/x/crypto to v0.31.0

---

test/e2e/templates/basic-cluster.yaml

Bump Kubernetes version for e2e tests

---

.github/workflows/scan.yaml

Run scan workflows for PRs against 2.10
Issue #
**Checklist**:

ci: Run scan workflows for PRs against 2.10

---

.github/workflows/build.yaml
.github/workflows/release.yaml
Makefile
package/Dockerfile
pkg/version/version.go

This PR changes the build process to be self-contained: it no longer requires the application to be build outside the container and relying on go version in the CI runner, instead the build is done in a build layer.
It also updates the release workflow to additionally push images to Prime Registry.
Finally it uses [cross-compilation helpers](https://github.com/tonistiigi/xx?tab=readme-ov-file#go--cgo) to invoke the Go compiler with the correct env vars for the target platform.
Issue #794 
**Checklist**:

ci: Make release SLSA compliant

---

.github/workflows/build.yaml
.github/workflows/release.yaml
Makefile
package/Dockerfile
pkg/version/version.go

(cherry picked from commit 3d9dd1668b47f22660cd6dc002863546b0840de1)
This PR changes the build process to be self-contained: it no longer requires the application to be build outside the container and relying on go version in the CI runner, instead the build is done in a build layer.
It also updates the release workflow to additionally push images to Prime Registry.
Finally it uses [cross-compilation helpers](https://github.com/tonistiigi/xx?tab=readme-ov-file#go--cgo) to invoke the Go compiler with the correct env vars for the target platform.
Issue #794 
**Checklist**:

[2.10] ci: Make release SLSA compliant

---

.github/workflows/e2e-branch.yaml
.github/workflows/e2e-workflow.yaml

Push test images to ghcr.io instead of ttl.sh.
Issue #
**Checklist**:

ci: Push test images to ghcr.io instead of ttl.sh

---

.github/workflows/e2e-branch.yaml

Fix yaml formatting causing error https://github.com/rancher/gke-operator/actions/runs/12763735104
Issue #
**Checklist**:

ci: Fix yaml formatting

---

.github/workflows/nightly-publish.yaml

Push nightly charts and images to ghcr.io
**Checklist**:

ci: Push nightly charts and images to ghcr.io

---

.github/workflows/release.yaml

[release-v2.9] added go get dispatch workflow step

---

.github/workflows/release.yaml

[release-v2.10] added go get dispatch workflow step

---

.github/workflows/release.yaml

[release-v2.11] added go get dispatch workflow step

---

.github/workflows/release.yaml

[main] added go get dispatch workflow step

---

.github/workflows/release.yaml
charts/gke-operator/Chart.yaml

bumped the chart version to support v1.12
Issue [#48796](https://github.com/rancher/rancher/issues/48796)
**Checklist**:

bumped the chart version to support v1.12

---

.github/dependabot.yaml

added step to ignore lasso for v2.11
Issue #
**Checklist**:

added step to ignore lasso for v2.11
