.drone.yml
Change the `manifest` step in drone to use the same golang image as the
`build` step. Change the `push` step to use the plugins/docker image
and update the configuration for that step.
=> Fix drone config for image manifest and publishing

.drone.yml
The docker-publish step already builds the image, so it doesn't need a
build step beforehand. The docker-build step doesn't make sense to run
on pull_request events since the Dockerfile pulls from the master branch
of the remote github repository and not the locally checked-out
repository, so just remove it so that it doesn't block pull requests.
=> Remove docker-build step

controller/gke-cluster-config-handler.go, internal/gke/client.go
The GKE handler in Rancher needs to be able to build an initial admin
kubeconfig in order to generate the first service account in the
cluster. Since gke-operator already knows how to get the credential
Secret and convert it to an OAuth2 token, it is convenient to expose
this as a public function that Rancher can use to authenticate to the
cluster.
=> Add controller.GetTokenSource function

controller/gke-cluster-config-handler.go, examples/cluster-basic.yaml, examples/cluster-full.yaml, examples/cluster-registered.yaml, examples/cluster.json, internal/gke/create.go, internal/gke/delete.go, internal/gke/relative_resource_name.go, internal/gke/update.go
In GKE, a cluster is created either in a Region or a Zone. The CRD
supports setting either and the controller validates that one but not
both is set. But without this patch, the operator was only respecting
the Region setting and never regarding the Zone. The examples also
incorrectly referred to an example Zone identifier in the Region
setting. This patch ensures that Zone will be used to identify the
cluster if it is used and fixes the examples to make sense.
=> Fix handling of region vs zone

examples/cluster-full.yaml
Not every attribute was covered in the cluster-full.yaml example. Add
the createSubnetwork and subnetworkName fields to the example and set
the cluster-level subnetwork field to empty to make the example work.
Relates to but does not fix https://github.com/rancher/rancher/issues/31662
=> Expand ipAllocation example

controller/gke-cluster-config-handler.go
The function that was supposed to set the FailureMessage status
attribute was not doing that. This change ensures the error from the
onChange handler is actually used and the cluster status is updated.
=> Fix recordError function

examples/cluster-basic.yaml, examples/cluster.json
Add missing fields "maintenanceWindow" and "management" to JSON example.
Simplify basic examples by leaving nodePool.config empty since it is a
nilable field. The cluster-full.yaml example contains a fully populated
node pool config.
=> Fix examples

controller/gke-cluster-config-handler.go, crds/gkeclusterconfig.yaml, internal/gke/create.go, pkg/apis/gke.cattle.io/v1/types.go
PrivateClusterConfig.PublicEndpoint and
PrivateClusterConfig.PrivateEndpoint are read-only informational
parameters in the GKE SDK[1]. They should never have been exposed as
configurable options here. Configuration of the public and private
endpoints is done via the EnablePrivateEndpoint toggle.
[1] https://pkg.go.dev/google.golang.org/api/container/v1#PrivateClusterConfig
=> Remove publicEndpoint and privateEndpoint

controller/gke-cluster-config-handler.go
Without this change, the CA secret gets created from the raw CA
certificate, which means the resulting Secret is base64-encoded one
time. This caused a problem in Rancher which, for EKS, was relying on
not having to manage the encoding at all[1], but was accidentally
changed when GKE support was added. This change simplifies the secret
generator to just use the CA cert from GKE as-is without decoding, and
Rancher will be fixed to also not reencode it.
[1] https://github.com/rancher/rancher/blob/9007198a6b122e9daa43e5adc391beed8292ad0e/pkg/controllers/management/eks/eks_cluster_handler.go#L497
[2] https://github.com/rancher/rancher/commit/a6f0b91b8ab00bb342080c3d715d6000c450f05c#diff-a774fa3e1a522b4a76b3f3b100a84fa19e2166a41ed9414ec37bf2c57e70ffa9R248
Needed by …
=> Fix CACert encoding

controller/gke-cluster-config-handler.go
When clusters are imported there might be a race condition where the
GKEClusterConfig Status doesn't successfully get saved on the first try
and the controller will retry on its own. Without this patch, if it does
this, it would reattempt to create the CA secret and end up failing
trying to do this. This change ensures that there is no reattempt to
create the same CA secret, which also helps ensure that if there is a
legitimate failure to update the cluster config's Status then that
failure message isn't clobbered by this unrelated error.
https://github.com/rancher/rancher/issues/31952
=> Ignore already exists error for CA Secret creation

controller/gke-cluster-config-handler.go
The operator logs an info message when cluster creation is started, but
gives no indication when a cluster is being imported. Add a log for when
a cluster import is starting.
=> Add log message for imported clusters

examples/cluster-basic.yaml, examples/cluster-full.yaml, examples/cluster.json
The minimal YAML and JSON examples should use example values that match
the upstream defaults, so change httpLoadBalancing and
horizontalPodAutoscaling to true for those samples. This will match the
default settings for a cluster created via the GKE console with no
parameters changed. This change updates the full example to set the
converse of these settings, and updates the JSON example to use the
minimalist settings for networkPolicyEnabled and networkPolicyConfig.
=> Fix clusterAddons examples

main.go
It occurred to me while writing the support training guide that we don't expose debug logs for this even though we log at the debug level sometimes.
=> Add a --debug flag

controller/gke-cluster-config-handler.go, go.mod, go.sum
The validateUpdate method was adopted from eks-provider and mimicked its
kubernetes version validation, which ensures the provided version is
valid Semver and that the control plane and node versions are within a
constrained range of each other. This was causing a problem with GKE
versions as it was not always parsing the Semver components correctly
and would result in a confusing and incorrect error message like:
versions for cluster [1.18.16-gke.300] and nodegroup [1.18.15-gke.1501] not compatible: all nodegroup kubernetes versionsmust be equal to or one minor version lower than the cluster kubernetes version
Rather than fix the version parsing, this change just removes this
validation. GKE does not place such strict constraints on the delta
between the control plane and node pool …
=> Remove version validation for updates

controller/gke-cluster-config-handler.go
Fix a typo that caused upstreamSpec to set enablePrivateEndpoint to the
wrong value.
https://github.com/rancher/rancher/issues/32241
=> Fix upstreamspec construction for private clusters

pkg/apis/gke.cattle.io/v1/types.go
Without this change, if a mistake is made in configuring
IPAllocationPolicy or MasterAuthorizedNetworksConfig during cluster
creation, GKE can reject it with an HTTP 400 response, but there is no
way to fix the mistake either in the UI or even with a direct PUT
request. This is due to the norman 'noupdate' tags for these attributes,
which causes updates to be ignored. This change removes the noupdate
tags so that the fields can be edited while the cluster has not been
created in GKE yet. Once a cluster exists in GKE (even if it is in an
error state) it is still not possible to update these fields, and the
operator reconciler loop will ignore them.
Partial fix for https://github.com/rancher/rancher/issues/32207
UI can use this to allow the user to edit a newly created cluster that does not …
=> Make networking attributes update-able

internal/gke/create.go
If a cluster is created by the operator in the same location with the
same name as a cluster that already exists in GKE but is not known to
Rancher, GKE will reject the request, but the cluster name cannot be
edited. This change improves the error message that will be surfaced in
the UI so that users know how to handle the problem.
https://github.com/rancher/rancher/issues/32292
=> Improve error message for create conflict

pkg/apis/gke.cattle.io/v1/types.go
Without this patch, norman doesn't properly interpret *string types as
*strings and instead converts them to strings in the generated client
code, which prevents clients from treating these fields as nilable. To
fix this, we add an explicit type declaration in the norman tag as well
as a 'notnullable' annotation. This is counterintuitively used on fields
we expressly want to be nullable because otherwise norman interprets
''*string' as nullable and adds another * creating '**string' which is
not what we want.
Fixing the type parsing in norman would cause too many knock-on effects
in the other generated types in Rancher.
https://github.com/rancher/rancher/issues/32440
=> Add norman annotations for *string fields

pkg/apis/gke.cattle.io/v1/types.go
This reverts commit 28a2914f3e3dd9472e0560b23a136466e9f962dd.
This change fixed the generated Go structs but broke the JSON schema.
The now nonnullable fields cannot be set to empty values, and sending
strings returns a validation error "InvalidType 422: Failed to find type
*string". Revert for now so we can find a different solution.
=> Revert "Add norman annotations for *string fields"

controller/gke-cluster-config-handler.go, internal/gke/update.go
* Retry on conflict during enqueueUpdate
It is very important for the status update to succeed here, otherwise
the update loop will be entered again unnecessarily. For the cluster
label update, this means that even if the labels were successfully
updated, the controller will try to update them again but fail due to
having an out of date label fingerprint.
* Add retries to UpdateLabels
Unlike other update actions, updating GKE cluster labels is so fast that
the cluster object does not enter a RECONCILING state, and so
when checkAndUpdate is reentered it proceeds to check all fields for
update again. However, it also lags a tiny amount and the label
fingerprint and labels on the upstreamSpec and even on the newly fetched
cluster object might be out of sync with the real cluster, and so an …
=> Fix label updates

charts/gke-operator-crd/templates/crds.yaml
The PR that added the chart to this repo accidentally removed the label
field from the CRD. This change adds the label field back.
=> Add label to CRD

pkg/apis/gke.cattle.io/v1/types.go
Opt into a new field type in norman that will convert `*string`s to
`{nullable: true, type: nullablestring}` in the API schema, and back to
`*string` in the generated client code. Without this, `*string`s get
translated to just `string` in the generated code, which breaks clients'
ability to set fields to nil.
https://github.com/rancher/rancher/issues/32440
=> Set norman type to 'nullablestring' for *strings

controller/gke-cluster-config-handler.go, internal/gke/create.go
The max pods setting is only available for VPC-native (alias IP)
clusters, so requiring to be set to something when UseIPAliases is false
will cause a validation error from GKE. This change loosens the
requirement that MaxPodsConstraint be non-nil on create, and fixes the
upstreamSpec builder to tolerate it not being set on the upstream
cluster.
https://github.com/rancher/rancher/issues/32585
=> Fix MaxPodsConstraint for routes-based cluster

scripts/package-helm
The chart version sed command was inadvertently overwriting the
rancher-version annotation. This change fixes that issue.
Issue:
https://github.com/rancher/rancher/issues/32293
=> Fix version sed for chart version

.gitignore, charts/gke-operator/templates/deployment.yaml, charts/gke-operator/values.yaml
When Rancher is installed on a cluster behind a proxy, the operator
should trust the proxy's certificate. It is passed to the deployment via
a secret the user should setup per the Rancher documentation.
Issue:
https://github.com/rancher/rancher/issues/31846
=> Add additional trusted CAs

controller/gke-cluster-config-handler.go, internal/gke/update.go
53dbce90 was an attempt to address the occurrence of resource conflict
errors during an UpdateStatus call to set the resource phase to
"updating". It helped reduce the frequency of this happening but it did
not fully address the issue because it was not the only place where the
resource state is updated.
The resource conflict error always occurs after an error has occurred
during the reconcile loop. Multiple status updates happen in quick
succession during a single loop, and upon entering the next loop, the
shared informer cache is not fully synced and the controller worker
fetches an out of date version of the resource object.
Without this change, when this happens, the recordError handler function
tries to continue persisting the error state to the resource object with
UpdateStatus, but …
=> Follow up on labels issues

pkg/apis/gke.cattle.io/v1/types.go
Opt into new "pointer" field attribute from norman that will convert any
type to a pointer in the generated client code. The generated client code
includes "omitempty" JSON tags, which means that for maps and slices,
unset and empty values are both sent to the server as unset, which
breaks the cluster create validation. With this change, there's now a
difference between a nil value and an empty allocated map or slice in the
client code. Strings can now also use this attribute instead of the
"nullablestrings" type (a85378a/2450a6e).
Depends on https://github.com/rancher/norman/pull/400
https://github.com/rancher/rancher/issues/32553
https://github.com/rancher/rancher/issues/32440
=> Use norman:"pointer" for nullable fields

pkg/gke/create.go
GKE rolled out a change that denies setting PrivateClusterConfig on
Cluster objects if they are not using private nodes, so update the
controller to conform with this.
Since PrivateClusterConfig is ignored if EnablePrivateNodes is false,
add validation to ensure the PrivateClusterConfig settings are valid.
https://github.com/rancher/rancher/issues/33241
=> Only send PrivateClusterConfig for private clusters

charts/gke-operator-crd/templates/crds.yaml, examples/cluster-basic.yaml, examples/cluster-full.yaml, examples/cluster.json, pkg/apis/gke.cattle.io/v1/types.go, pkg/apis/gke.cattle.io/v1/zz_generated_deepcopy.go, pkg/gke/create.go
Tags represent firewall rules applied to each node. Node tags cannot be
modified after the cluster is created.
https://cloud.google.com/vpc/docs/add-remove-network-tags
Also updated the kubernetes version in the examples for testing.
https://github.com/rancher/rancher/issues/33406
=> Add support for network tags

charts/gke-operator/templates/deployment.yaml, package/Dockerfile, package/entrypoint.sh
The SLE image requires that c_rehash is run before additional trusted
CAs will be detected. Therefore, an entrypoint script is added to
accomplish this.
In addition, fsGroup is added so that c_rehash (which is run as the
gke-operator user) can read the cert that is mounted.
Issue:
https://github.com/rancher/rancher/issues/31846
=> Run c_rehash before launch the operator

controller/gke-cluster-config-handler.go, internal/gke/create.go
This reverts commit 4116b88151723e008f4c4e1fff14762d48654a47.
This bugfix will appear in the 1.1.x series.
=> Revert "Fix MaxPodsConstraint for routes-based cluster"

controller/gke-cluster-config-handler.go
Without this, the true value of the nodepool tags was appearing empty in
the upstream spec.
https://github.com/rancher/rancher/issues/33406
=> Add Tags to upstream spec builder

charts/gke-operator/templates/_helpers.tpl, charts/gke-operator/values.yaml
Rancher sets the default registry under
`global.cattle.systemDefaultRegistry`. Without this change, the chart
wasn't picking up the setting and would still try to pull images from
dockerhub. This change aligns the setting with the way Rancher expects
to use it and with the way other charts expose it.
https://github.com/rancher/rancher/issues/35485
=> Fix system default registry setting

charts/gke-operator/Chart.yaml
The annotations were also rearranged to be in alphabetical order.
Issue:
https://github.com/rancher/rancher/issues/35100
=> Add kube-version annotation to chart

pkg/apis/gke.cattle.io/v1/types.go
Address https://github.com/rancher/rancher/issues/36128.
A KEv2 cluster imported with the rancher2 terraform provider will currently delete all node groups on import if no node groups are specified in the terraform config.
This is happening because the `NodeGroups` cluster config field (and all slices and maps) in the KEv2 operators have the `norman:pointer` tag. The problem is that the `norman:pointer` tag is added to fields that are already pointers. When node groups is not specified in the terraform config, terraform sets the node group field in the management cluster yaml as an empty array instead of null. If node groups is an empty array, Rancher deletes all node groups from the imported cluster because that is the template given: no node groups. Removing the incorrect tag will make …
=> Remove norman:pointer tags from GKE operator

charts/gke-operator/templates/deployment.yaml, charts/gke-operator/values.yaml
Related to https://github.com/rancher/rancher/issues/37927
The purpose of this PR is to add the ability to set a priorityClassName for pods installed by rancher cluster.
=> Adds priorityClassName to deployments.

README.md
- When releasing unRC'ed version of the operator, the version should stay the same and not bump to a new minor version
- some minor improvement on notes related to tagging (with signature and annotation)
=> 📖 Clarify a bit more tagging a release in root README.md

.github/dependabot.yaml
Removes unnecessary prow related labelling [comment](https://github.com/rancher/gke-operator/pull/116#issuecomment-1540072329) on dependabot PRs which is configured in the dependabot configuration
=> 🐛 Remove unnecessary labelling from dependabot configuration

Dockerfile.dapper, package/Dockerfile
The base image `bci-base` is updated from `15.4` to `15.5` to fix the vulnerabilities reported by rancherlabs/image-scanning#2285 on the latest release of the operator.
=> fix: bump base image for bci-base to 15.5

.github/workflows/nightly-publish.yaml
This adds a new GHA workflow that builds the operator image every night and publishes it to ttl.sh.
=> chore: added nightly publish of image for testing

.github/dependabot.yaml
**What this PR does / why we need it:**
We have to check outdated dependency also for `release-v2.8` and `release-v2.7` branches
=> Improve dependabot to track other branches

.github/workflows/nightly-publish.yaml
This uses the reusable workflow to publish charts nightly to ttl.sh, as we do with other operators.
Issue #137 
The reusable workflow's last step `build-push-chart` is failing because of operator version conflicts between rancher:v2.8 and the operator main branch. Issue https://github.com/rancher-sandbox/highlander-reusable-workflows/issues/2 keeps track of this.
**Checklist**:
=> chore: publish charts nightly with reusable workflow

.github/workflows/e2e-latest-rancher.yaml, .github/workflows/e2e.yaml, README.md, test/e2e/config/config.go, test/e2e/suite_test.go, test/e2e/templates/basic-cluster.yaml
e2e tests locally are passing since the user is expected to change the `projectID` value in the `GKEClusterConfig` cluster template. However, e2e tests running daily in the GitHub Actions also need to replace that value, hence it was missing till now. This PR ensures the new `GKE_PROJECT_ID` var is created and passed to the cluster template later and replaces it with the actual value from GH secret `GKE_PROJECT_ID`. This should fix e2e tests currently broken
https://github.com/rancher/gke-operator/actions/workflows/e2e-latest-rancher.yaml
Fixes: #264 
Follow-up to: https://github.com/rancher/gke-operator/pull/256
Tested the changes in my fork and tests are passing: …
=> Fix e2e daily tests

.github/workflows/apidiff.yaml, .github/workflows/build.yaml, .github/workflows/e2e.yaml, .github/workflows/lint.yaml, .github/workflows/unit.yaml, .github/workflows/verify.yaml, Dockerfile.dapper, go.mod, test/e2e/Dockerfile.e2e, test/e2e/config/config.go
=> Bump go version to 1.21

controller/gke-cluster-config-handler_test.go
Don't check error during creating namaspaces, due to namespace usage limitation https://book.kubebuilder.io/reference/envtest.html#namespace-usage-limitation
Issue #
**Checklist**:
=> Fix unit tests

Dockerfile.dapper, package/Dockerfile
Issue: https://github.com/rancher/gke-operator/issues/368 (cherry picked from commit 8d2a7d499603abe8cda121d5e55875c6999f1b18)
Issue #
**Checklist**:
=> [v2.7] security: bump operator base image to bci-micro:15.5

Dockerfile.dapper, package/Dockerfile
Issue: https://github.com/rancher/gke-operator/issues/368 (cherry picked from commit 8d2a7d499603abe8cda121d5e55875c6999f1b18)
Issue #
**Checklist**:
=> [v2.8] security: bump operator base image to bci-micro:15.5

.github/workflows/apidiff.yaml, .github/workflows/e2e-branch.yaml, .github/workflows/update-rancher-charts.yaml, .github/workflows/update-rancher-dep.yaml, Makefile
Replace unapproved GH Actions with approved ones. To [enhance security](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions), the 3rd-party GH Action used to install kind is pinned to a commit SHA. Note that dependabot will [update](https://github.com/dependabot/dependabot-core/issues/4691) both the commit SHA and the human-readable value next to it.
Issue https://github.com/rancher/highlander/issues/89
**Checklist**:
=> fix: Replace unapproved GH Actions with approved ones

.github/workflows/apidiff.yaml, .github/workflows/lint.yaml, .github/workflows/update-rancher-charts.yaml, .github/workflows/update-rancher-dep.yaml, Makefile
Replace unapproved GH Actions with approved ones. To [enhance security](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions), the 3rd-party GH Action used to install kind is pinned to a commit SHA. Note that dependabot will [update](https://github.com/dependabot/dependabot-core/issues/4691) both the commit SHA and the human-readable value next to it.
Issue https://github.com/rancher/highlander/issues/89
- actions/setup-go has been updated to v5 to eliminate Node runtime version warnings
- Upon checkout, credentials are not being persisted since the git commands will occur on a different repo (bot's fork)
**Checklist**:
=> [v2.9] fix: Replace unapproved GH Actions with approved ones

.github/workflows/apidiff.yaml, .github/workflows/build.yaml, .github/workflows/lint.yaml, .github/workflows/nightly-publish.yaml, .github/workflows/scan.yaml, .github/workflows/update-rancher-charts.yaml, .github/workflows/update-rancher-dep.yaml, .github/workflows/verify.yaml, Makefile
Replace unapproved GH Actions with approved ones. To [enhance security](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions), the 3rd-party GH Action used to install kind is pinned to a commit SHA. Note that dependabot will [update](https://github.com/dependabot/dependabot-core/issues/4691) both the commit SHA and the human-readable value next to it.
Issue https://github.com/rancher/highlander/issues/89
- actions/checkout has been updated to v4 to eliminate Node runtime version warnings
- actions/setup-go has been updated to v5 to eliminate Node runtime version warnings
- Upon checkout, credentials are not being …
=> [v2.8] fix: Replace unapproved GH Actions with approved ones

.github/workflows/apidiff.yaml, .github/workflows/build.yaml, .github/workflows/lint.yaml, .github/workflows/nightly-publish.yaml, .github/workflows/scan.yaml, .github/workflows/update-rancher-charts.yaml, .github/workflows/update-rancher-dep.yaml, .github/workflows/verify.yaml, .trivyignore, Dockerfile.dapper, Makefile
Replace unapproved GH Actions with approved ones. To [enhance security](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions), the 3rd-party GH Action used to install kind is pinned to a commit SHA. Note that dependabot will [update](https://github.com/dependabot/dependabot-core/issues/4691) both the commit SHA and the human-readable value next to it.
Issue https://github.com/rancher/highlander/issues/89
- actions/checkout has been updated to v4 to eliminate Node runtime version warnings
- actions/setup-go has been updated to v5 to eliminate Node runtime version warnings
- Upon checkout, credentials are not being …
=> [v2.7] fix: Replace unapproved GH Actions with approved ones

test/e2e/templates/basic-cluster.yaml
Updates the k8s version for the test cluster used in e2e tests.
**Checklist**:
=> fix: Update k8s version for e2e test cluster

.github/workflows/e2e-branch.yaml, .github/workflows/e2e-workflow.yaml
Fixed tagging of the images built by CI that are used for e2e tests. Currently, the image tag is always using the commit of the `main` branch (as that branch is used to run the e2e workflow for all releases we maintain) regardless of the branch for which the e2e tests are executing. After this change, the tag will use the commit of each branch.
Also removed the e2e tests for 2.7 as this is going into maintenance mode.
Example test run: https://github.com/yiannistri/gke-operator/actions/runs/9549828162
**Checklist**:
=> Fix e2e workflow

controller/gke-cluster-config-handler_test.go, pkg/gke/delete_test.go, pkg/gke/update_test.go
Issue: https://github.com/rancher/gke-operator/issues/526
Issue #
**Checklist**:
=> [v2.9] Drop support for Kubernetes v1.25 and v1.26

.github/workflows/release.yaml, .goreleaser.yaml
Up until recently, creating a new GitHub release (and associated artifacts) when a new tag was created, was being done using Drone CI. Now that Drone CI has been deprecated, there is a GitHub Actions workflow that is responsible for doing this. In fact, most of the work is delegated to goreleaser which is being invoked as part of that workflow.
Issue #538
=> ci: Add goreleaser config and update release workflow

.drone.yml, .github/workflows/release.yaml, .gitignore, .goreleaser.yaml, .trivyignore
Up until recently, creating a new GitHub release (and associated artifacts) when a new tag was created, was being done using Drone CI. Now that Drone CI has been deprecated, there is a GitHub Actions workflow that is responsible for doing this. In fact, most of the work is delegated to goreleaser which is being invoked as part of that workflow.
Cherry pick of the commit of https://github.com/rancher/gke-operator/pull/540
Issue #538
**Checklist**:
=> [v2.7] ci: Add goreleaser config and update release workflow

.github/scripts/update-rancher-charts.sh, .github/workflows/update-rancher-charts.yaml
Updated workflow to show dropdown options for selecting target branch and tested the release script. Note that this is not yet 100% complete as the last step is to create a PR from the bot's branch. However, merging this PR will allow us to test the creation of the remote branch (which requires bot token access).
After merging this PR:
- a user can select the target 'rancher/charts' branch to create a PR against
- a user specifies old/new version of chart and operator and whether the new version replaces the old one
- the release script will run and update a local branch with the requested changes
Still left to do:
- push local branch into bot's remote
- create PR from bot's remote
Issue #96 
**Checklist**:
=> ci: Show dropdown options for selecting target branch

.github/workflows/update-rancher-charts.yaml
Once this PR gets merged, whenever a user invokes this workflow, a new PR will be opened against the rancher/charts with the changes necessary to update the operator version.
Issue #96 
**Checklist**:
=> ci: Create PR against rancher/charts

.github/workflows/update-rancher-charts.yaml
Use the `gh` cli to create a PR. The equivalent GH action that is currently used [is failing](https://github.com/rancher/gke-operator/actions/runs/9841742752).
Issue #96 
**Checklist**:
=> ci: Use `gh` cli to create PR

.github/workflows/release.yaml
Specify the exact tag for the new release. This is necessary because by default, goreleaser sorts tags by name before selecting which tag to release, which causes problems when >1 tags point to the same commit (un-rc process). From https://goreleaser.com/cookbooks/set-a-custom-git-tag/
Issue #565 
**Checklist**:
=> ci: Specify the exact tag for the new release

.github/workflows/release.yaml
Specify the exact tag for the new release. This is necessary because by default, goreleaser sorts tags by name before selecting which tag to release, which causes problems when >1 tags point to the same commit (un-rc process). From https://goreleaser.com/cookbooks/set-a-custom-git-tag/
Issue #565 
**Checklist**:
=> [v2.9] ci: Specify the exact tag for the new release 

test/e2e/templates/basic-cluster.yaml
Update manifest used for e2e test to use a supported version of Kubernetes in GKE.
**Checklist**:
=> ci: Bump GKE k8s version to fix failing tests

test/e2e/templates/basic-cluster.yaml
Update manifest used for e2e test to use a supported version of Kubernetes in GKE.
**Checklist**:
=> [v2.9] ci: Bump GKE k8s version to fix failing tests

test/e2e/templates/basic-cluster.yaml
Update manifest used for e2e test to use a supported version of Kubernetes in GKE.
**Checklist**:
=> [v2.8] Bump gke version for e2e release v2.8

.gitignore, charts/gke-operator/templates/deployment.yaml, charts/gke-operator/values.yaml
Propagates the debug log flag so that it can be set on the gke-operator's helm chart. By default, it is set to false.
Issue #511 
**Checklist**:
=> Propagate debug log flag

.gitignore, charts/gke-operator/templates/deployment.yaml, charts/gke-operator/values.yaml
Propagates the debug log flag so that it can be set on the gke-operator's helm chart. By default, it is set to false.
Issue #511 
**Checklist**:
=> [v2.8] Propagate debug log flag

.gitignore, charts/gke-operator/templates/deployment.yaml, charts/gke-operator/values.yaml
Propagates the debug log flag so that it can be set on the gke-operator's helm chart. By default, it is set to false.
Issue #511 
**Checklist**:
=> [v2.9] Propagate debug log flag

controller/gke-cluster-config-handler.go, controller/gke-cluster-config-handler_test.go, pkg/gke/create.go, pkg/gke/update.go
Enhancing the logs:
- [cluster-name (cluster-id)] > [cluster-name (id:cluster-id)]
- Use structs instead of pointers to print data
- Remove upstream data from info log
- Add debug info
- Update nodepool name duplicate error
Signed-off-by: Parthvi <parthvi.vala@suse.com>
(cherry picked from commit 1675d2bff28f9177288e9bf5207c0a3f3edfb872)
Issue #
**Checklist**:
=> [v2.9] Enhance the logs

test/e2e/templates/basic-cluster.yaml
The current version of Kubernetes used for e2e tests is no longer supported.
**Checklist**:
=> fix: Update e2e k8s version

test/e2e/templates/basic-cluster.yaml
(cherry picked from commit 08014af8f5b8d34b8ccf13f8e9b2a5c224d97e43)
The current version of Kubernetes used for e2e tests is no longer supported.
**Checklist**:
=> [v2.8] fix: Update e2e k8s version

test/e2e/templates/basic-cluster.yaml
(cherry picked from commit 08014af8f5b8d34b8ccf13f8e9b2a5c224d97e43)
The current version of Kubernetes used for e2e tests is no longer supported.
**Checklist**:
=> [v2.9] fix: Update e2e k8s version

.github/workflows/release.yaml, .github/workflows/scan.yaml, .trivyignore, package/Dockerfile
Bump base image version to 15.6. Also updated release and scan workflows to use the same version of Go, which is the one specified in go.mod.
**Checklist**:
=> [v2.7] Bump image version

.github/workflows/release.yaml, .github/workflows/scan.yaml, .trivyignore
We bump the version of the Go compiler used to build the operator itself in order to protect from any vulnerabilities that are present in older versions of the compiler. Note that we intentionally do not bump the version of the Go module as it's imported by Rancher 2.7.
The list of CVEs addressed:
- CVE-2023-45288
- CVE-2024-24790
- CVE-2024-34156
**Checklist**:
=> ci: Use Go 1.23 to build binary

.github/workflows/scan.yaml
We frequently get CI failures when scanning with trivy because there have been too many requests to download the vulnerability db from the rancher org (because many of its repos are using it).
This PR updates the Scan workflow to include additional repositories to be used if trivy fails to retrieve the vulnerability db from the primary source.
Issue #703 
Source for fix: https://github.com/aquasecurity/trivy/discussions/7668#discussioncomment-10884984
**Checklist**:
=> ci: Fix trivy action timeout

Makefile, package/Dockerfile
Backport of #783 
Issue #782 
**Checklist**:
=> [v2.8] VEX related improvements in the build process

.github/workflows/build.yaml, .github/workflows/release.yaml, Makefile, package/Dockerfile, pkg/version/version.go
(cherry picked from commit 3d9dd1668b47f22660cd6dc002863546b0840de1)
This PR changes the build process to be self-contained: it no longer requires the application to be build outside the container and relying on go version in the CI runner, instead the build is done in a build layer.
It also updates the release workflow to additionally push images to Prime Registry.
Finally it uses [cross-compilation helpers](https://github.com/tonistiigi/xx?tab=readme-ov-file#go--cgo) to invoke the Go compiler with the correct env vars for the target platform.
Issue #794 
**Checklist**:
=> [2.9] ci: Make release SLSA compliant

.github/workflows/build.yaml, .github/workflows/release.yaml, Makefile, package/Dockerfile, pkg/version/version.go
(cherry picked from commit 3d9dd1668b47f22660cd6dc002863546b0840de1)
This PR changes the build process to be self-contained: it no longer requires the application to be build outside the container and relying on go version in the CI runner, instead the build is done in a build layer.
It also updates the release workflow to additionally push images to Prime Registry.
Finally it uses [cross-compilation helpers](https://github.com/tonistiigi/xx?tab=readme-ov-file#go--cgo) to invoke the Go compiler with the correct env vars for the target platform.
Issue #794 
**Checklist**:
=> [2.8] ci: Make release SLSA compliant

.github/workflows/lint.yaml, .golangci.yml
- `skip-pkg-cache` is removed in golangci lint.  [Reference](https://github.com/golangci/golangci-lint-action/tree/0bc16cda6e51961f4eb7c2ee2a92b0a4a5ddfd4b?tab=readme-ov-file#compatibility)
- `run.skip-dirs` is deprecated and is replaced by `issues.exclude-dirs` . [Reference](https://github.com/golangci/golangci-lint/pull/4509)
- https://github.com/rancher/gke-operator/actions/runs/13360664115/job/37309809267?pr=829
=> Update and remove deprecated config

.github/workflows/delete-old-versions.yaml
Implement a scheduled workflow to automatically delete outdated images and charts for the gke-operator, retaining only the specified minimum versions.
=> [main] Add workflow to delete old images and charts for gke-operator

.github/workflows/release.yaml, charts/gke-operator/Chart.yaml
- Add support for auto chart bump in release GHA
- New charts will be pushed to the branch with the name chart/[MAJOR-VERSION].[MINOR-VERSION]
- Bump `rancher-version` and `kube-version`
- https://github.com/rancher/rancher/issues/49164
=> [v2.11] Add support for auto chart bump in release GHA

.github/workflows/release.yaml, charts/gke-operator/Chart.yaml
- Add support for auto chart bump in release GHA
- New charts will be pushed to the branch with the name chart/[MAJOR-VERSION].[MINOR-VERSION]
- Bump `rancher-version` and `kube-version`
- https://github.com/rancher/rancher/issues/49164
=> [v2.10] Add support for auto chart bump in release GHA

.github/workflows/release.yaml, charts/gke-operator/Chart.yaml
- Add support for auto chart bump in release GHA
- New charts will be pushed to the branch with the name chart/[MAJOR-VERSION].[MINOR-VERSION]
- Bump `rancher-version` and `kube-version`
- https://github.com/rancher/rancher/issues/49164
=> [v2.9] Add support for auto chart bump in release GHA
